name = "f2w-frontend"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "domain-monitor"
database_id = "8b21eb9b-08fb-47e5-889c-cd2a68181e0b"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "CACHE"
id = "00ca0b8ef45143f6aede0d5dd2d32e65"

[vars]
SITE_URL = "https://52weekchallenge.app"
