name = "52weeks-monitoring"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[triggers]
crons = ["0 0 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "domain-monitor"
database_id = "8b21eb9b-08fb-47e5-889c-cd2a68181e0b"

[vars]
AWS_REGION = "sa-east-1"
SES_FROM_EMAIL = "domains@messages.ambiente1.com.br"
VAPID_PUBLIC_KEY = "BBCZlBnq4VxwJTkCL08C1zrafpvOSBTFMPwHXHlfAm3kTNadoR8WNTRfajZGdR6mrMIDvxRpBMlwJYbygssrMUE"
VAPID_SUBJECT = "mailto:domains@messages.ambiente1.com.br"

# Secrets: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, SES_FROM_EMAIL, VAPID_PRIVATE_KEY

