name = "f2w-monitoring"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[triggers]
crons = ["0 0 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "domain-monitor"
database_id = "8b21eb9b-08fb-47e5-889c-cd2a68181e0b"

[vars]
AWS_REGION = "us-east-1"
VAPID_PUBLIC_KEY = "BHQo40sM6T0s4mZVsqHJc05pPbVy8TYFhuSTUAY2nsqFNP3uMwKaBRlaf2pqdeyHWSfrHEm4i9sieIdXu7k21Xc"
VAPID_SUBJECT = "mailto:domains@ambiente1.com.br"

# Secrets: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, SES_FROM_EMAIL, SNS_PLATFORM_ARN, VAPID_PRIVATE_KEY
